# Generated by Django 5.1.1 on 2025-03-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="items_per_page",
            field=models.CharField(
                choices=[("decimal", "Decimal"), ("american", "American")],
                default=20,
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="odds_preference",
            field=models.CharField(
                choices=[("decimal", "Decimal"), ("american", "American")],
                default="decimal",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="remove_color_from_tables",
            field=models.BooleanField(default=False),
        ),
    ]
