# Generated by Django 5.1.1 on 2025-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_items_per_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="items_per_page",
            field=models.CharField(
                choices=[("10", 10), ("20", 20), ("50", 50), ("no", "No Pagination")],
                default="20",
                max_length=8,
            ),
        ),
    ]
