services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=kpUyhaYEOtFsWF9UOSyZeayZ-aPGXmccd4HDAbaMFxRBBpgi45s"
      #- "DJANGO_DEBUG=False"
      #- "DJANGO_SECURE_SSL_REDIRECT=False"
      #- "DJANGO_SECURE_HSTS_SECONDS=0" # new
      #- "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" # new
      #- "DJANGO_SECURE_HSTS_PRELOAD=False" # new
      #- "DJANGO_SESSION_COOKIE_SECURE=False" # new
      #- "DJANGO_CSRF_COOKIE_SECURE=False" # new
  db:
    image: postgres:13
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
