# Generated by Django 5.1.1 on 2024-09-17 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=25)),
                ('pick', models.CharField(max_length=25)),
                ('amount_wagered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game_time', models.DateField()),
                ('result', models.CharField(max_length=2)),
                ('bet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
