# Generated by Django 5.1.1 on 2024-09-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='amount_wagered',
            new_name='stake',
        ),
    ]
