# Generated by Django 5.1.1 on 2024-09-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_bet_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='pick',
            field=models.CharField(max_length=50),
        ),
    ]
