# Generated by Django 5.1.1 on 2024-10-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_bet_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='game_time',
            new_name='event_date',
        ),
    ]
