# Generated by Django 5.1.1 on 2024-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_rename_game_time_bet_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='site',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
