# Generated by Django 5.1.1 on 2024-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_alter_bet_event_date_alter_bet_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='site',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
