# Generated by Django 5.1.1 on 2024-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_alter_bet_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('bet_associated', models.ManyToManyField(to='bets.bet')),
            ],
        ),
    ]
