# Generated by Django 5.1.1 on 2024-10-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
