# Generated by Django 5.1.1 on 2024-10-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0011_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('associated_bet', models.ManyToManyField(to='bets.bet')),
            ],
        ),
    ]
