# Generated by Django 5.1.1 on 2024-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('associated_bets', models.ManyToManyField(blank=True, to='bets.bet')),
            ],
        ),
    ]
