# Generated by Django 5.1.1 on 2024-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_initial'),
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='associated_bets',
            field=models.ManyToManyField(blank=True, related_name='tags', to='bets.bet'),
        ),
    ]
